import array
import time
from pathlib import Path


class FlatfieldMixin:
    def _flatfield_matches_current_cube(self, info=None):
        info = info or self.current_hypercube_info
        if not info or not self.flatfield_hypercube_handle or not self.flatfield_info:
            return False
        keys = ("source_width", "source_height", "width", "height", "bands", "data_type", "display_roi")
        return all(info.get(key) == self.flatfield_info.get(key) for key in keys)

    def _should_use_flatfield_correction(self, info=None):
        return bool(self.use_flatfield_var.get()) and self._flatfield_matches_current_cube(info)

    def _export_normalized_envi_from_cubes(self, sample_handle, flatfield_handle, output_base_path, description, info):
        width = info["width"]
        height = info["height"]
        source_width = info.get("source_width", width)
        source_height = info.get("source_height", height)
        display_roi = info.get("display_roi")
        bands = info["bands"]
        data_type = info["data_type"]
        raw_path = output_base_path
        hdr_path = output_base_path + ".hdr"
        wavelengths = []

        with open(raw_path, "wb") as raw_file:
            for band_index in range(bands):
                wavelength, sample_values = self.controller.get_hypercube_band_data(
                    sample_handle,
                    band_index,
                    source_width,
                    source_height,
                    data_type,
                )
                _, flat_values = self.controller.get_hypercube_band_data(
                    flatfield_handle,
                    band_index,
                    source_width,
                    source_height,
                    data_type,
                )
                sample_values = self._crop_hyper_band_values_for_display(sample_values, source_width, display_roi)
                flat_values = self._crop_hyper_band_values_for_display(flat_values, source_width, display_roi)
                normalized = array.array(
                    "f",
                    (
                        float(sample) / float(flat) if abs(float(flat)) > 1e-12 else 0.0
                        for sample, flat in zip(sample_values, flat_values)
                    ),
                )
                normalized.tofile(raw_file)
                wavelengths.append(wavelength)

        safe_description = (description or "Generated by AppHeraTriggerPython0417").replace("}", ")")
        wavelength_text = ", ".join(f"{wavelength:.6f}" for wavelength in wavelengths)
        header = (
            "ENVI\n"
            f"description = {{{safe_description}}}\n"
            f"samples = {width}\n"
            f"lines = {height}\n"
            f"bands = {bands}\n"
            "header offset = 0\n"
            "file type = ENVI Standard\n"
            "data type = 4\n"
            "interleave = bsq\n"
            "byte order = 0\n"
            f"wavelength = {{{wavelength_text}}}\n"
        )
        Path(hdr_path).write_text(header, encoding="utf-8")
        return hdr_path

    def start_flatfield_acquisition(self):
        try:
            tag = self._sanitize_export_tag(f"flatfield_{time.strftime('%Y%m%d_%H%M%S')}")
            self._arm_and_start_acquisition(export_tag=tag, acquisition_role="flatfield")
        except Exception as exc:
            self.log(f"Failed to start flatfield acquisition: {exc}")
            self.update_state("Error")

    def clear_flatfield(self):
        if self.flatfield_hypercube_handle and self.controller:
            try:
                if self.current_hypercube_handle != self.flatfield_hypercube_handle:
                    self.controller.release_hypercube(self.flatfield_hypercube_handle)
            except Exception:
                pass
        self.flatfield_hypercube_handle = None
        self.flatfield_info = None
        self.flatfield_status_var.set("Flatfield: none")
        self.current_hyper_band_cache = {}
        self.current_hyper_spectrum_cache = {}
        self.log("Flatfield cleared.")
        self.render_current_hyper_band()
